baseurl = "https://luluslly.xyz"
enableEmoji = true
footnotereturnlinkcontents = "â†©"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Home"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "witchhazel"
tabWidth = 2

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2
[[menu.feed]]
name = "Socials"
url = "/socials/"
weight = 2
[[menu.feed]]
name = "RSS"
url = "/index.xml"
weight = 3
[[menu.feed]]
name = "donate"
url = "/donate/"
weight = 1

[params]
custom_css = ["css/theme-override.css"]
description = "Digital mischief, analog heart."
footer = """
<div style="display: flex; justify-content: center; align-items: center; gap: 10px; flex-wrap: wrap;">
    <img src="/images/think_different_powered_by_mac.gif" alt="Think Different Powered by Mac" class="footer-gif">
    <img src="/images/linux_powered.gif" alt="Linux Powered" class="footer-gif">
    <img src="/images/under_construction.gif" alt="This page is perpetually under construction" class="footer-gif">
    <img src="/images/matrix.gif" alt="Matrix numbers scrolling across the screen" class="footer-gif">
    <img src="/images/this_page_may_be_hazardous_to_your_health.gif" alt="Warning! This page may be hazardous to your mental health" class="footer-gif">
    <p>
        <a href="https://spyware.neocities.org/">
        <img src="/images/online_spyware_watchdog.png" alt="Online Spyware Watchdog">
    </p>
    <p>
        <a href="https://lucida.to/">
        <img src="/images/freemusicnow.png" alt="Lucida">
    </p>
</div>

<style>
    .footer-gif {
        width: 120px;
        height: 60px;
        object-fit: contain;
        flex-shrink: 0;
        flex-grow: 0;
    }

    .footer-gif-large {
        width: 100px;
        height: 80px;
    }
</style>
"""
